### ISSUE TITLE
FSP Proposal Feedback

### ISSUE THREAD

**Issue by andywynkoop** [jnapolitan/Towncloud#1]
Hey Julian, this looks pretty great so far, here are a few changes I'd like you to make:
# Home Page
- [x] Your logo is awesome
- [x] Add a placeholder link to the live site (update once you deploy for the first time)
- [x] Add links to the other wiki pages
# MVP List
- [x] Don't forget about error handling and styling for each MVP 
- [x] Is a 'tag' like a category? if so, it should probably be it's own MVP (don't worry about implementing this until you add this feature)
- [x] I think that searching is really its own MVP, especially if you plan to use filters like location and taggings. For the song and artist CRUD features, just worry about making an index route for now and add the search feature as a bonus. We can talk about this in more detail tomorrow.
# DB Schema
- [x] These graphics are dope, what do you use to make them?
- [x] If users can sign in via email as well, it might be a good idea to index this column
- [x] Also, if you plan to search for users by location, this should probably be indexed as well, but if we decide it should be a bonus then don't bother including it until you get there
- [x] In the songs table, anything you plan on searching by should be indexed to improve performance (but again let's talk about search later)
# API routes
- [x] You'll probably want some kind of index route for users if you plan on having any kind of artist index page (and you'll definitely need it if you're searching for artists)
# Front end routes
- [x] You should think about how you'll distinguish regular users from artists on both the front end and the back end – when viewing the artist index page, you'll want to make sure you aren't returning "artists" that don't have any songs
- [x] What is the difference between an artist and a user? Do you need both a sign up form and a new artist form? Show pages? How does Soundcloud handle this?

This looks great, let me know if you have any questions! Let's also set up a time to meet tomorrow to go over your plan in more detail.

**Comment by jnapolitan** [comment]
Hey Andy, thanks for the feedback! Definitely looking forward to chatting more tomorrow, but in the meantime wanted to answer a couple of your q's as best I could:

Regular users and artists are synonymous on Soundcloud as far as I can tell, and with the exception of some artists being legit/verified/etc..either way the functionality seems essentially the same. All users are artists in that they have the ability to create/upload songs, but not all do, so I think your point about not surfacing users/artists with no songs posted is a really good call for the UX.

Also, I wasn't planning on implementing search as an MVP (but if you think it would be valuable, I'm all for it). The location feature would be more passive, like the ArtistIndex component could filter ArtistIndexItems to a user's location automatically, so initially it would only display local artists and users can choose to browse all artists if they wanted to. 

For tags, on SC each song only has one tag and clicking on that tag takes you to a view of other songs with the same tag. If you think it makes sense to add that as it's own MVP I could move some other stuff around.

Looking forward to chatting more tomorrow! And glad you like the logo, I made it in a Lyft from Oakland to San Francisco last night. And for the schema graphic I used [SQLDMB](https://sqldbm.com/Home/). I think only the first one's free but I haven't really looked at their pricing. All the other DB visualizers I've seen are kind of garbage (might be an opportunity to build something there).

**Comment by jnapolitan** [comment]
Actually I'm wrong about tags...looks like each song has one *main* tag (maybe more of a category?) which is prominently displayed on the song show page, and then there's the option to add what looks like sub-tags as well (not as obvious on the show page). I was planning on just sticking to the one main tag, I originally had both tags and taggings tables and then thought it might be a good idea to dial that back.
